### ISSUE TITLE
Add Top Header to all .cpp and .h files

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k-PlatformIO#21]
Need to add the following info and header to all code files:

The below doesn't need to be exact but is just a starting basis.  

/*
SmartSpin2K code

This software registers an ESP32 as a BLE FTMS device which then uses a stepper motor to turn the resistance knob on a regular spin bike. 

BLE code based on examples from https://github.com/nkolban

 Copyright 2020 Anthony Doud
  
 This work is licensed under the GNU General Public License v2
*/

**Comment by cancellogic** [comment]
Done.  Caveats: no for autogenerated code and no for files that appear to be original unaltered work of a third party (BLE?),
